My_basecamp_2-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  resources :comments

  resources :filers
  resources :attaches
  resources :todos

  resources :projects do
  resources :todos
  resources :filers
  resources :messages
  end
  root 'pages#home'
end

My_basecamp_2-main/app/models/message.rb
class Message < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy
end

My_basecamp_2-main/app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update destroy ]

  # GET /messages or /messages.json
  def index
    @project = Project.find(params[:project_id])
    @messages = @project.messages.all
  end

  # GET /messages/1 or /messages/1.json
  def show
    @comments = @message.comments.order(created_at: :desc)
  end

  # GET /messages/new
  def new
    @project = Project.find(params[:project_id])
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
    # @project = Project.find(params[:project_id])
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to message_url(@message), notice: "Message was successfully created." }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to message_url(@message), notice: "Message was successfully updated." }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1 or /messages/1.json
  def destroy
    @message.destroy
@project = @message.project_id
    if @message.destroy
      redirect_to project_messages_path(@project)
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:name, :description, :project_id)
    end
end

My_basecamp_2-main/app/helpers/messages_helper.rb
module MessagesHelper
end

My_basecamp_2-main/app/views/messages/_edit_form.html.erb
<%= form_with(model: message) do |form| %>
<div class="overlay">
       <div class="con">
       <header class="head-form">
          <h2>Create Message</h2>
          <p>You Can Create Message</p>
       </header>
       <br>
       <div class="field-set">
             <span class="input-item">
             </span>
             <%= form.text_field :name, class:"form-input", placeholder: "Message Name" %>
          <br>
          <span class="input-item">
             </span>
              <%= form.text_field :description, class:"form-input", placeholder: "Message Description"  %>
         <br />
          <br>
          <button type="submit" class="log-in"> Update Message </button>
       </div>
       <div>
  <%= link_to "Back to message",message_path(@message.id), style: "text-decoration: none;" %>
</div>
      </div>
     <% end %>
    </div>



<style>
    /* Fonts Form Google Font ::- https://fonts.google.com/  -:: */
    @import url('https://fonts.googleapis.com/css?family=Abel|Abril+Fatface|Alegreya|Arima+Madurai|Dancing+Script|Dosis|Merriweather|Oleo+Script|Overlock|PT+Serif|Pacifico|Playball|Playfair+Display|Share|Unica+One|Vibur');
    /* End Fonts */
    /* Start Global rules */
   
    /* End Global rules */
    
  
    
    
    
    /* |||||||||||||||||||||||||||||||||||||||||||||*/
    /* //////////////////////////////////////////// */
    
    
    
    
    /* End body rules */
    
    /* Start form  attributes */
    form {
        width: 450px;
        min-height: 500px;
        height: auto;
        border-radius: 5px;
        margin: 2% auto;
        box-shadow: 0 9px 50px hsla(20, 67%, 75%, 0.31);
        padding: 2%;
        background-image: linear-gradient(-225deg, #E3FDF5 50%, #FFE6FA 50%);
    }
    /* form Container */
    form .con {
        display: -webkit-flex;
        display: flex;
      
        -webkit-justify-content: space-around;
        justify-content: space-around;
      
        -webkit-flex-wrap: wrap;
        flex-wrap: wrap;
      
          margin: 0 auto;
    }
    
    /* the header form form */
    header {
        margin: 2% auto 10% auto;
        text-align: center;
    }
    /* Login title form form */
    header h2 {
        font-size: 250%;
        font-family: 'Playfair Display', serif;
        color: #3e403f;
    }
    /*  A welcome message or an explanation of the login form */
    header p {letter-spacing: 0.05em;}
    
    
    
    /* //////////////////////////////////////////// */
    /* //////////////////////////////////////////// */
    
    
    .input-item {
        background: #fff;
        color: #333;
        padding: 14.5px 0px 15px 9px;
        border-radius: 5px 0px 0px 5px;
    }
    
    
    
    /* Show/hide password Font Icon */
    #eye {
        background: #fff;
        color: #333;
      
        margin: 5.9px 0 0 0;
        margin-left: -20px;
        padding: 15px 9px 19px 0px;
        border-radius: 0px 5px 5px 0px;
      
        float: right;
        position: relative;
        right: 1%;
        top: -.2%;
        z-index: 5;
        
        cursor: pointer;
    }
    /* inputs form  */
    input[class="form-input"]{
        width: 270px;
        height: 50px;
      
        margin-top: 2%;
        padding: 15px;
        
        font-size: 16px;
        font-family: 'Abel', sans-serif;
        color: #5E6472;
      
        outline: none;
        border: none;
      
        border-radius: 0px 5px 5px 0px;
        transition: 0.2s linear;
        
    }
    input[id="txt-input"] {width: 250px;}
    /* focus  */
    input:focus {
        transform: translateX(-2px);
        border-radius: 5px;
    }
    
    /* //////////////////////////////////////////// */
    /* //////////////////////////////////////////// */
    
    /* input[type="text"] {min-width: 250px;} */
    /* buttons  */
    button {
        display: inline-block;
        color: #252537;
      
        width: 280px;
        height: 50px;
      
        padding: 0 20px;
        background: #fff;
        border-radius: 5px;
        
        outline: none;
        border: none;
      
        cursor: pointer;
        text-align: center;
        transition: all 0.2s linear;
        
        margin: 7% auto;
        letter-spacing: 0.05em;
    }
    /* Submits */
    .submits {
        width: 48%;
        display: inline-block;
        float: left;
        margin-left: 2%;
    }
    
    /*       Forgot Password button FAF3DD  */
    .frgt-pass {background: transparent;}
    
    /*     Sign Up button  */
    .sign-up {background: #B8F2E6;}
    
    
    /* buttons hover */
    button:hover {
        transform: translatey(3px);
        box-shadow: none;
    }
    
    /* buttons hover Animation */
    button:hover {
        animation: ani9 0.4s ease-in-out infinite alternate;
    }
    @keyframes ani9 {
        0% {
            transform: translateY(3px);
        }
        100% {
            transform: translateY(5px);
        }
    }
    
    </style>
    

My_basecamp_2-main/app/views/messages/_form.html.erb
<%= form_with(model: message) do |form| %>
<div class="overlay">
       <div class="con">
       <header class="head-form">
          <h2>Create Message</h2>
          <p>You Can Create Message</p>
       </header>
       <br>
       <div class="field-set">
             <span class="input-item">
             </span>
             <%= form.text_field :name, class:"form-input", placeholder: "Message Name" %>
          <br>
        <%= form.number_field :project_id, value: @project.id, type: :hidden %>

                 <span class="input-item">
             </span>
              <%= form.text_field :description, class:"form-input", placeholder: "Message Description"  %>
         <br />
         
         
          <br>
          <button type="submit" class="log-in"> Creat Message </button>
       </div>
       <div>
  <%= link_to "Back to messages", project_messages_path(@project.id),style: "text-decoration: none;" %>
</div>
      </div>
     <% end %>
    </div>



<style>
    /* Fonts Form Google Font ::- https://fonts.google.com/  -:: */
    @import url('https://fonts.googleapis.com/css?family=Abel|Abril+Fatface|Alegreya|Arima+Madurai|Dancing+Script|Dosis|Merriweather|Oleo+Script|Overlock|PT+Serif|Pacifico|Playball|Playfair+Display|Share|Unica+One|Vibur');
    /* End Fonts */
    /* Start Global rules */
   
    /* End Global rules */
    
  
    
    
    
    /* |||||||||||||||||||||||||||||||||||||||||||||*/
    /* //////////////////////////////////////////// */
    
    
    
    
    /* End body rules */
    
    /* Start form  attributes */
    form {
        width: 450px;
        min-height: 500px;
        height: auto;
        border-radius: 5px;
        margin: 2% auto;
        box-shadow: 0 9px 50px hsla(20, 67%, 75%, 0.31);
        padding: 2%;
        background-image: linear-gradient(-225deg, #E3FDF5 50%, #FFE6FA 50%);
    }
    /* form Container */
    form .con {
        display: -webkit-flex;
        display: flex;
      
        -webkit-justify-content: space-around;
        justify-content: space-around;
      
        -webkit-flex-wrap: wrap;
        flex-wrap: wrap;
      
          margin: 0 auto;
    }
    
    /* the header form form */
    header {
        margin: 2% auto 10% auto;
        text-align: center;
    }
    /* Login title form form */
    header h2 {
        font-size: 250%;
        font-family: 'Playfair Display', serif;
        color: #3e403f;
    }
    /*  A welcome message or an explanation of the login form */
    header p {letter-spacing: 0.05em;}
    
    
    
    /* //////////////////////////////////////////// */
    /* //////////////////////////////////////////// */
    
    
    .input-item {
        background: #fff;
        color: #333;
        padding: 14.5px 0px 15px 9px;
        border-radius: 5px 0px 0px 5px;
    }
    
    
    
    /* Show/hide password Font Icon */
    #eye {
        background: #fff;
        color: #333;
      
        margin: 5.9px 0 0 0;
        margin-left: -20px;
        padding: 15px 9px 19px 0px;
        border-radius: 0px 5px 5px 0px;
      
        float: right;
        position: relative;
        right: 1%;
        top: -.2%;
        z-index: 5;
        
        cursor: pointer;
    }
    /* inputs form  */
    input[class="form-input"]{
        width: 270px;
        height: 50px;
      
        margin-top: 2%;
        padding: 15px;
        
        font-size: 16px;
        font-family: 'Abel', sans-serif;
        color: #5E6472;
      
        outline: none;
        border: none;
      
        border-radius: 0px 5px 5px 0px;
        transition: 0.2s linear;
        
    }
    input[id="txt-input"] {width: 250px;}
    /* focus  */
    input:focus {
        transform: translateX(-2px);
        border-radius: 5px;
    }
    
    /* //////////////////////////////////////////// */
    /* //////////////////////////////////////////// */
    
    /* input[type="text"] {min-width: 250px;} */
    /* buttons  */
    button {
        display: inline-block;
        color: #252537;
      
        width: 280px;
        height: 50px;
      
        padding: 0 20px;
        background: #fff;
        border-radius: 5px;
        
        outline: none;
        border: none;
      
        cursor: pointer;
        text-align: center;
        transition: all 0.2s linear;
        
        margin: 7% auto;
        letter-spacing: 0.05em;
    }
    /* Submits */
    .submits {
        width: 48%;
        display: inline-block;
        float: left;
        margin-left: 2%;
    }
    
    /*       Forgot Password button FAF3DD  */
    .frgt-pass {background: transparent;}
    
    /*     Sign Up button  */
    .sign-up {background: #B8F2E6;}
    
    
    /* buttons hover */
    button:hover {
        transform: translatey(3px);
        box-shadow: none;
    }
    
    /* buttons hover Animation */
    button:hover {
        animation: ani9 0.4s ease-in-out infinite alternate;
    }
    @keyframes ani9 {
        0% {
            transform: translateY(3px);
        }
        100% {
            transform: translateY(5px);
        }
    }
    
    </style>
    

My_basecamp_2-main/app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render "edit_form", message: @message %>

<br>

<div>
  <%= link_to "Show this message", @message %> |
  <%= link_to "Back to messages", messages_path %>
</div>

My_basecamp_2-main/app/views/messages/index.html.erb
<br><h2 align="center">
<a class="header" style="text-decoration: none; color: rgb(129, 103, 169);" href=" <%= new_project_message_path(@project.id) %> ">
<button class="button-34">
New Message
</button>
</a>
</h2>

<a href="/projects/<%= @project.id %>"  >
<button class="button-34" style="background: #bd2193c2;">
Back
</button>
</a>

<div class="wrapper">



  <div class="header">
	  <% if @messages.count > 0 %>
	
        <h1 class="header__title">You Have <%= pluralize @messages.count, "Message" %></h1>
  <% else %>
      <h1 class="header__title">You Don't Have Any Messages! </h1>

  <% end %>
  </div>

  <div class="cards">

<% @messages.each do |message| %>

    <div class=" card [ is-collapsed ] ">
      <div class="card__inner [ js-expander ]">
       <a href="/messages/<%= message.id %> " style="text-decoration: none;color: #6610f2;"> <span><%= message.name %></span></a>
	   <br>
        <i class="fa fa-folder-o"></i>
      </div>
    </div>
<% end %>

     


  </div>

</div>


<style>
@charset "UTF-8";
/* CSS */
.button-34 {
  background: #5E5DF0;
  border-radius: 999px;
  box-shadow: #5E5DF0 0 10px 20px -10px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  font-family: Inter,Helvetica,"Apple Color Emoji","Segoe UI Emoji",NotoColorEmoji,"Noto Color Emoji","Segoe UI Symbol","Android Emoji",EmojiSymbols,-apple-system,system-ui,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans",sans-serif;
  font-size: 16px;
  font-weight: 700;
  line-height: 24px;
  opacity: 1;
  outline: 0 solid transparent;
  padding: 8px 18px;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  width: fit-content;
  word-break: break-word;
  border: 0;
}
.wrapper {
  margin: 5em auto;
  max-width: 1000px;
  background-color: #fff;
  box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.06);
}
.header__title {
	 margin: 0;
	 text-transform: uppercase;
	 font-size: 2.5em;
	 font-weight: 500;
	 line-height: 1.1;
}
 .header__subtitle {
	 margin: 0;
	 font-size: 1.5em;
	 color: #949fb0;
	 font-family: 'Yesteryear', cursive;
	 font-weight: 500;
	 line-height: 1.1;
}
 .cards {
	 padding: 15px;
	 display: flex;
	 flex-flow: row wrap;
}
 .card {
	 margin: 15px;
	 width: calc((100% / 3) - 30px);
	 transition: all 0.2s ease-in-out;
}
 @media screen and (max-width: 991px) {
	 .card {
		 width: calc((100% / 2) - 30px);
	}
}
 @media screen and (max-width: 767px) {
	 .card {
		 width: 100%;
	}
}
 .card:hover .card__inner {
	 background-color: #8167a9;
	 transform: scale(1.05);
}
 .card__inner {
	 width: 100%;
	 padding: 30px;
	 position: relative;
	 cursor: pointer;
	 background-color: #212121;
	 color: #eceef1;
	 font-size: 1.5em;
	 text-transform: uppercase;
	 text-align: center;
	 transition: all 0.2s ease-in-out;
	 height: 142%;
}
 .card__inner:after {
	 transition: all 0.3s ease-in-out;
}
 .card__inner .fa {
	 width: 100%;
	 margin-top: 0.25em;
}
 .card__expander {
	 transition: all 0.2s ease-in-out;
	 background-color: #333a45;
	 width: 100%;
	 position: relative;
	 display: flex;
	 justify-content: center;
	 align-items: center;
	 text-transform: uppercase;
	 color: #eceef1;
	 font-size: 1.5em;
}
 .card__expander .fa {
	 font-size: 0.75em;
	 position: absolute;
	 top: 10px;
	 right: 10px;
	 cursor: pointer;
}
 .card__expander .fa:hover {
	 opacity: 0.9;
}
 .card.is-collapsed .card__inner:after {
	 content: "";
	 opacity: 0;
}
 .card.is-collapsed .card__expander {
	 max-height: 0;
	 min-height: 0;
	 overflow: hidden;
	 margin-top: 0;
	 opacity: 0;
}
 .card.is-expanded .card__inner {
	 background-color: #1abc9c;
}
 .card.is-expanded .card__inner:after {
	 content: "";
	 opacity: 1;
	 display: block;
	 height: 0;
	 width: 0;
	 position: absolute;
	 bottom: -30px;
	 left: calc(50% - 15px);
	 border-left: 15px solid transparent;
	 border-right: 15px solid transparent;
	 border-bottom: 15px solid #333a45;
}
 .card.is-expanded .card__inner .fa:before {
	 content: "\f115";
}
 .card.is-expanded .card__expander {
	 max-height: 1000px;
	 min-height: 200px;
	 overflow: visible;
	 margin-top: 30px;
	 opacity: 1;
}
 .card.is-expanded:hover .card__inner {
	 transform: scale(1);
}
 .card.is-inactive .card__inner {
	 pointer-events: none;
	 opacity: 0.5;
}
 .card.is-inactive:hover .card__inner {
	 background-color: #949fb0;
	 transform: scale(1);
}
 @media screen and (min-width: 992px) {
	 .card:nth-of-type(3n+2) .card__expander {
		 margin-left: calc(-100% - 30px);
	}
	 .card:nth-of-type(3n+3) .card__expander {
		 margin-left: calc(-200% - 60px);
	}
	 .card:nth-of-type(3n+4) {
		 clear: left;
	}
	 .card__expander {
		 width: calc(300% + 60px);
	}
}
 @media screen and (min-width: 768px) and (max-width: 991px) {
	 .card:nth-of-type(2n+2) .card__expander {
		 margin-left: calc(-100% - 30px);
	}
	 .card:nth-of-type(2n+3) {
		 clear: left;
	}
	 .card__expander {
		 width: calc(200% + 30px);
	}
}
</style>

My_basecamp_2-main/app/views/messages/new.html.erb
<%= render "form", message: @message %>

<br>

My_basecamp_2-main/app/views/messages/show.html.erb
<h1 align="center"><%= @message.name %></h1>
<p align="center"><%= @message.description %></p>

<div>

	<a href="<%= project_messages_path(@message.project_id) %>"  >
<button class="button-34" style="background: #bd2193c2;">
Back
</button>
</a>

<% if @message.project.user_id == current_user.id %>
  
<%= link_to edit_message_path(@message),style: "text-decoration: none;" do %>
<button class="button-34">Edit</button>
<% end %>

<%= button_to "Destroy", @message, method: :delete, onclick: "return confirm('Are You Sure Delete This Message!')", style: "float: right;background: #bd2193c2;margin-top: -40px;" ,class: "button-34" %>
<% end %>


</div>



<div class="container">
  <%= render 'comments/form', 
    message: @message, 
    comment: @message.comments.build,
    submit_label: "Reply" %>
  <% @comments.each do |comment| %>
    <%= render 'comments/comment', 
    message: @message, 
    comment: comment %>
  <% end %>
</div>


<style>
.button-34 {
  background: #5E5DF0;
  border-radius: 999px;
  box-shadow: #5E5DF0 0 10px 20px -10px;
  box-sizing: border-box;
  color: #FFFFFF;
  cursor: pointer;
  font-family: Inter,Helvetica,"Apple Color Emoji","Segoe UI Emoji",NotoColorEmoji,"Noto Color Emoji","Segoe UI Symbol","Android Emoji",EmojiSymbols,-apple-system,system-ui,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans",sans-serif;
  font-size: 16px;
  font-weight: 700;
  line-height: 24px;
  opacity: 1;
  outline: 0 solid transparent;
  padding: 8px 18px;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  width: fit-content;
  word-break: break-word;
  border: 0;
}
</style>