My_basecamp_2-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  resources :comments

  resources :filers
  resources :attaches
  resources :todos

  resources :projects do
  resources :todos
  resources :filers
  resources :messages
  end
  root 'pages#home'
end

My_basecamp_2-main/app/models/filer.rb
class Filer < ApplicationRecord
  belongs_to :project
  has_one_attached :attach
  validates :description , presence: true
end

My_basecamp_2-main/app/controllers/filers_controller.rb
class FilersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_filer, only: [:show, :edit, :update, :destroy]

  # GET projects/1/tasks
  def index
    # @filer = Filer.find[:id]
    @filers = @project.filers

  end

  # GET projects/1/tasks/1
  def show
      
  end

  # GET projects/1/tasks/new
  def new
    @filer = @project.filers.build
    @filers = @project.filers
  end

  # GET projects/1/tasks/1/edit
  def edit
  end

  # POST projects/1/tasks
  def create
    @filer = @project.filers.build(filer_params)

    if @filer.save
      redirect_to new_project_filer_path
    end
  end

  # PUT projects/1/tasks/1
  def update
    if @filer.update(filer_params)
      redirect_to new_project_filer_path
    else
      render action: 'edit'
    end
  end

  # DELETE projects/1/tasks/1
  def destroy
      @filer.destroy
          redirect_to new_project_filer_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_filer
      @filer = @project.filers.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def filer_params
      params.require(:filer).permit(:description, :project_id, :attach)
    end
end

My_basecamp_2-main/app/helpers/filers_helper.rb
module FilersHelper
end

My_basecamp_2-main/app/views/filers/_filer.html.erb
<div id="<%= dom_id filer %>">
 <% if filer.persisted? %>
                <tr>
                  <td>
                <% if filer.attach.attached? %>
                <% if  filer.attach.image?%>
                                    <h2 class="entry-title"><a href="#"><%= link_to image_tag(filer.attach, class: "img_upload"),  rails_blob_path(filer.attach, disposition: "attachment") %>
                  
                      <% elsif filer.attach.audio? %>
                                    <h2 class="entry-title"><a href="#"><%= filer.attach.filename %>
                                      <audio controls>
                                       <source src=" <%= rails_blob_url(filer.attach, disposition: "attachment") %>" type="audio/mpeg"/>
                                       </audio></a></h2>
                   <% else %>
                  <h2 class="entry-title"><a href="#"><%= link_to filer.attach.filename,  rails_blob_path(filer.attach, disposition: "attachment") %></a></h2>
                                        
                  <% end %>
                  
                  <% end %>
                  
                  </td>
                  <td><%= filer.description %></td>
          
                </tr>
                <% end %>
</div>

My_basecamp_2-main/app/views/filers/_form.html.erb
<div class="div_edit_task">
<%= form_for([@filer.project, @filer]) do |f| %>
  <% if @filer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@filer.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @filer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.file_field :attach, required: true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit "Edit", class: "btn btn-primary"%> <br />
<%= link_to "Back", new_project_todo_path(@project) %>

  </div>
<% end %>
</div>

My_basecamp_2-main/app/views/filers/edit.html.erb
<div align="center" style="font-size: 30px;">
<h1>Update Attachment</h1>
<div>
<br>
<%= form_for([@filer.project, @filer]) do |f| %>
  <div style="width: 100%;display: flex;justify-content: center;margin-bottom: 2rem;"class="container">
    <div align="center" style="display: flex;justify-content: center; width: 90%;background-color: #ffffff;border-radius: 10rem;box-shadow: 0 0 1rem #dddcdc;overflow: hidden;transition: width 1s;">
      <%= f.text_field :description, id: "form1",style: "width: 100%; padding: 0 2rem; outline: none;border: none;font-size: 2rem;", required: true %>
      <%= f.file_field :attach, id: "form1",style: "width: 100%; padding: 0 2rem; outline: none;border: none;font-size: 2rem;margin-top: 8px;", required: true %>
      <%= f.submit "Create", style: "text-transform: none;border: none;background-image: linear-gradient(to right bottom, rgb(199, 188, 217), rgb(129, 103, 169)); color: #32383d; font-weight: 700;font-size: 2rem;display: inline-block;text-decoration: none;transition: all 0.5s;position: relative;border: none;cursor: pointer;"%>
    </div>
  </div>
  </div>
</div>

<% end %>


<a href="<%= new_project_filer_path(@project) %>"  >
  <button class="button-34" style="background: #bd2193c2;">
    Back
  </button>
</a>
</div>

<style>
  .button-34 {
    background: #5E5DF0;
    border-radius: 999px;
    box-shadow: #5E5DF0 0 10px 20px -10px;
    box-sizing: border-box;
    color: #FFFFFF;
    cursor: pointer;
    font-family: Inter,Helvetica,"Apple Color Emoji","Segoe UI Emoji",NotoColorEmoji,"Noto Color Emoji","Segoe UI Symbol","Android Emoji",EmojiSymbols,-apple-system,system-ui,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans",sans-serif;
    font-size: 16px;
    font-weight: 700;
    line-height: 24px;
    opacity: 1;
    outline: 0 solid transparent;
    padding: 8px 18px;
    user-select: none;
    -webkit-user-select: none;
    touch-action: manipulation;
    width: fit-content;
    word-break: break-word;
    border: 0;
  }
</style>

My_basecamp_2-main/app/views/filers/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Filers</h1>

<div id="filers">
  <% @filers.each do |filer| %>
    <%= render filer %>
    <p>
      <%= link_to "Show this filer", filer %>
    </p>
  <% end %>
</div>

<%= link_to "New filer", new_filer_path %>

My_basecamp_2-main/app/views/filers/new.html.erb
<br>
<%= form_for([@filer.project, @filer]) do |f| %>
  <div style="width: 100%;display: flex;justify-content: center;margin-bottom: 2rem;"class="container">
    <div align="center" style="display: flex;justify-content: center; width: 90%;background-color: #ffffff;border-radius: 10rem;box-shadow: 0 0 1rem #dddcdc;overflow: hidden;transition: width 1s;">
      <%= f.text_field :description, id: "form1", placeholder: "Description",style: "width: 100%; padding: 0 2rem; outline: none;border: none;font-size: 2rem;", required: true %>
      <%= f.file_field :attach, id: "form1",style: "width: 100%; padding: 0 2rem; outline: none;border: none;font-size: 2rem;margin-top: 8px;", required: true %>
      <%= f.submit "Create", style: "text-transform: none;border: none;background-image: linear-gradient(to right bottom, rgb(199, 188, 217), rgb(129, 103, 169)); color: #32383d; font-weight: 700;font-size: 2rem;display: inline-block;text-decoration: none;transition: all 0.5s;position: relative;border: none;cursor: pointer;"%>
    </div>
  </div>
  </div>
</div>
  
<% end %>
<a href="<%= project_path(@project) %>"  >
  <button class="button-34" style="background: #bd2193c2;">
    Back
  </button>
</a>
<% if @filers.count > 0 %>
  <div class="wrapper">
    <div class="header">
    </div>
    <div class="cards">
      <% @filers.each do |filer| %>
        <% if filer.persisted? %>
          <% if filer.attach.attached? %>
            <div class=" card [ is-collapsed ] ">
              <div class="card__inner [ js-expander ]">
                <a > <span><%= link_to filer.attach.filename,  rails_blob_path(filer.attach, disposition: "attachment"), style: "text-decoration: none;color: #6610f2;" %></span></a> <br>
                <br>
                <%= filer.description %> <br>
                <% if  filer.attach.image?%> <br>
                  <i class="bi bi-file-earmark-image"></i>
                <% elsif  filer.attach.video?%> <br>
                  <i class="bi bi-file-earmark-play"></i>
                <% elsif  filer.attach.audio?%> <br>
                  <i class="bi bi-file-music-fill"></i>
                <% else %> <br>
                  <i class="bi bi-files"></i>
                <% end %> <br>
 <br>
                <%= link_to [filer.project, filer], 'data-turbo-method': :delete, onclick: "return confirm('Are You Sure!')" ,style: "float: right;color: #bd2193c2;" do %>
                  <i class="bi bi-trash2"></i>
                <% end %>
                <%= link_to edit_project_filer_path(filer.project, filer),style: "float: left; color: #6610f2;"  do %>
                  <i class="bi bi-pen"></i>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>
<style>
  @charset "UTF-8";
  .wrapper {
    margin: 5em auto;
    max-width: 1000px;
    background-color: #fff;
    box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.06);
  }
  .button-34 {
    background: #5E5DF0;
    border-radius: 999px;
    box-shadow: #5E5DF0 0 10px 20px -10px;
    box-sizing: border-box;
    color: #FFFFFF;
    cursor: pointer;
    font-family: Inter,Helvetica,"Apple Color Emoji","Segoe UI Emoji",NotoColorEmoji,"Noto Color Emoji","Segoe UI Symbol","Android Emoji",EmojiSymbols,-apple-system,system-ui,"Segoe UI",Roboto,"Helvetica Neue","Noto Sans",sans-serif;
    font-size: 16px;
    font-weight: 700;
    line-height: 24px;
    opacity: 1;
    outline: 0 solid transparent;
    padding: 8px 18px;
    user-select: none;
    -webkit-user-select: none;
    touch-action: manipulation;
    width: fit-content;
    word-break: break-word;
    border: 0;
  }
  .header__title {
  	 margin: 0;
  	 text-transform: uppercase;
  	 font-size: 2.5em;
  	 font-weight: 500;
  	 line-height: 1.1;
  }
   .header__subtitle {
  	 margin: 0;
  	 font-size: 1.5em;
  	 color: #949fb0;
  	 font-family: 'Yesteryear', cursive;
  	 font-weight: 500;
  	 line-height: 1.1;
  }
   .cards {
  	 padding: 15px;
  	 display: flex;
  	 flex-flow: row wrap;
  }
   .card {
  	 margin: 15px;
  	 width: calc((100% / 3) - 30px);
  	 transition: all 0.2s ease-in-out;
  }
   @media screen and (max-width: 991px) {
  	 .card {
  		 width: calc((100% / 2) - 30px);
  	}
  }
   @media screen and (max-width: 767px) {
  	 .card {
  		 width: 100%;
  	}
  }
   .card:hover .card__inner {
  	 background-color: #8167a9;
  	 transform: scale(1.05);
  }
   .card__inner {
  	 width: 100%;
  	 padding: 30px;
  	 position: relative;
  	 cursor: pointer;
  	 background-color: #212121;
  	 color: #eceef1;
  	 font-size: 1.5em;
  	 text-transform: uppercase;
  	 text-align: center;
  	 transition: all 0.2s ease-in-out;
  	 height: 142%;
  }
   .card__inner:after {
  	 transition: all 0.3s ease-in-out;
  }
   .card__inner .fa {
  	 width: 100%;
  	 margin-top: 0.25em;
  }
   .card__expander {
  	 transition: all 0.2s ease-in-out;
  	 background-color: #333a45;
  	 width: 100%;
  	 position: relative;
  	 display: flex;
  	 justify-content: center;
  	 align-items: center;
  	 text-transform: uppercase;
  	 color: #eceef1;
  	 font-size: 1.5em;
  }
   .card__expander .fa {
  	 font-size: 0.75em;
  	 position: absolute;
  	 top: 10px;
  	 right: 10px;
  	 cursor: pointer;
  }
   .card__expander .fa:hover {
  	 opacity: 0.9;
  }
   .card.is-collapsed .card__inner:after {
  	 content: "";
  	 opacity: 0;
  }
   .card.is-collapsed .card__expander {
  	 max-height: 0;
  	 min-height: 0;
  	 overflow: hidden;
  	 margin-top: 0;
  	 opacity: 0;
  }
   .card.is-expanded .card__inner {
  	 background-color: #1abc9c;
  }
   .card.is-expanded .card__inner:after {
  	 content: "";
  	 opacity: 1;
  	 display: block;
  	 height: 0;
  	 width: 0;
  	 position: absolute;
  	 bottom: -30px;
  	 left: calc(50% - 15px);
  	 border-left: 15px solid transparent;
  	 border-right: 15px solid transparent;
  	 border-bottom: 15px solid #333a45;
  }
   .card.is-expanded .card__inner .fa:before {
  	 content: "\f115";
  }
   .card.is-expanded .card__expander {
  	 max-height: 1000px;
  	 min-height: 200px;
  	 overflow: visible;
  	 margin-top: 30px;
  	 opacity: 1;
  }
   .card.is-expanded:hover .card__inner {
  	 transform: scale(1);
  }
   .card.is-inactive .card__inner {
  	 pointer-events: none;
  	 opacity: 0.5;
  }
   .card.is-inactive:hover .card__inner {
  	 background-color: #949fb0;
  	 transform: scale(1);
  }
   @media screen and (min-width: 992px) {
  	 .card:nth-of-type(3n+2) .card__expander {
  		 margin-left: calc(-100% - 30px);
  	}
  	 .card:nth-of-type(3n+3) .card__expander {
  		 margin-left: calc(-200% - 60px);
  	}
  	 .card:nth-of-type(3n+4) {
  		 clear: left;
  	}
  	 .card__expander {
  		 width: calc(300% + 60px);
  	}
  }
   @media screen and (min-width: 768px) and (max-width: 991px) {
  	 .card:nth-of-type(2n+2) .card__expander {
  		 margin-left: calc(-100% - 30px);
  	}
  	 .card:nth-of-type(2n+3) {
  		 clear: left;
  	}
  	 .card__expander {
  		 width: calc(200% + 30px);
  	}
  }
</style>

My_basecamp_2-main/app/views/filers/show.html.erb
<p style="color: green"><%= notice %></p>
<div align="center">
  <% if @filer.persisted? %>
    <% if @filer.attach.attached? %>
      <div class="card" style="width: 25rem;">
        <% if  @filer.attach.image?%>
          <%= link_to image_tag(@filer.attach, class: "card-img-top"),  rails_blob_path(@filer.attach, disposition: "attachment") %>
        </div>
        <div>
        <% else %>
          <h2 class="entry-title"><a href="#"><%= link_to @filer.attach.filename,  rails_blob_path(@filer.attach, disposition: "attachment") %></a></h2>
        <% end %>
        <div class="card-body">
          <h5 class="card-title" style="margin-top: 12%;"><%= @filer.description %></h5>
          <%= link_to "Back", new_project_filer_path(@project), class: "btn btn-primary", style: "margin-top: 12%;"  %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>