My_basecamp_2-main/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :comments
  end
  resources :comments

  resources :filers
  resources :attaches
  resources :todos

  resources :projects do
  resources :todos
  resources :filers
  resources :messages
  end
  root 'pages#home'
end

My_basecamp_2-main/app/models/todo.rb
class Todo < ApplicationRecord
  belongs_to :project
  validates :name , presence: true

end

My_basecamp_2-main/app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_todo, only: [:show, :edit, :update, :destroy]

  # GET projects/1/todos
  def index
    @todos = @project.todos.order(created_at: :desc)
  end

  # GET projects/1/todos/1
  def show
      @users = User.all
  end

  # GET projects/1/todos/new
  def new
    @todo = @project.todos.build
    @todos = @project.todos
  end

  # GET projects/1/todos/1/edit
  def edit
  end

  # POST projects/1/todos
  def create
    @todo = @project.todos.build(todo_params)

    if @todo.save
      redirect_to new_project_todo_path
    else
      render action: 'new'
    end
  end

  # PUT projects/1/todos/1
  def update
    if @todo.update(todo_params)
      redirect_to new_project_todo_path
    end
  end

  # DELETE projects/1/todos/1
  def destroy
      @todo.destroy
          redirect_to new_project_todo_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_todo
      @todo = @project.todos.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

My_basecamp_2-main/app/views/todos/_form.html.erb
<div align="center" style="font-size: 30px;">
<div class="div_edit_task">
<%= form_for([@todo.project, @todo]) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_area :name%>
  </div>
  <div class="actions">
    <%= f.submit "Edit", class: "btn btn-primary"%>
  </div>
  <div>
<%= link_to "Back", new_project_todo_path(@project) %>
  
  </div>
<% end %>
</div>
</div>

My_basecamp_2-main/app/views/todos/_todo.html.erb
<div id="<%= dom_id task %>">
  <p>
    <strong>Name:</strong>
    <%= task.name %>
  </p>

  <p>
    <strong>Project:</strong>
    <%= task.project_id %>
  </p>

</div>

My_basecamp_2-main/app/views/todos/edit.html.erb
<h1 align="center">Editing todo</h1>
<div align="center">

  <h5 style="margin-left: 22px;"><%= link_to "Back", new_project_todo_path(@project), style: "margin-left: 22px; color: #8167a9ff; text-decoration: none;" %></h5>

<%= form_for([@todo.project, @todo]) do |f| %>
  <div style="width: 100%;display: flex;justify-content: center;margin-bottom: 2rem;"class="container">
    <div align="center" style="display: flex;justify-content: center; width: 90%;background-color: #ffffff;border-radius: 10rem;box-shadow: 0 0 1rem #dddcdc;overflow: hidden;transition: width 1s;">
      <%= f.text_field :name, id: "form1",style: "width: 100%; padding: 0 2rem; outline: none;border: none;font-size: 2rem;", required: true %>
      <%= f.submit "Creat todo", style: "text-transform: none;border: none;background-image: linear-gradient(to right bottom, rgb(199, 188, 217), rgb(129, 103, 169)); color: #32383d; font-weight: 700;font-size: 2rem;display: inline-block;text-decoration: none;transition: all 0.5s;position: relative;border: none;cursor: pointer;"%>
    </div>
  </div>
<% end %>
</div>

My_basecamp_2-main/app/views/todos/index.html.erb
<h1>Listing tasks</h1>

<table>
  <tr>
    <th>Description</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @todos.each do |task| %>
<% if task.persisted? %>
  <tr>
    <td><%= task.name %></td>
    <td><%= task.project %></td>
    <td><%= link_to 'Show', [task.project, task], class: "btn btn-info" %></td>
    <td><%= link_to 'Edit', edit_project_task_path(task.project, task) %></td>
    <td><%= link_to 'Destroy', [task.project, task], 'data-turbo-method': :delete %></td>
  </tr>
<% end %>
<% end %>
</table>

<br />

<%= link_to 'New Task', new_project_todo_path(params[:project_id]) %>

My_basecamp_2-main/app/views/todos/new.html.erb
   
<h1 align="center">Todos</h1>
<%= form_for([@todo.project, @todo]) do |f| %>
  <div style="width: 100%;display: flex;justify-content: center;margin-bottom: 2rem;"class="container">
    <div align="center" style="display: flex;justify-content: center; width: 90%;background-color: #ffffff;border-radius: 10rem;box-shadow: 0 0 1rem #dddcdc;overflow: hidden;transition: width 1s;">
      <%= f.text_field :name, id: "form1",style: "width: 100%; padding: 0 2rem; outline: none;border: none;font-size: 2rem;", required: true %>
      <%= f.submit "Creat todo", style: "text-transform: none;border: none;background-image: linear-gradient(to right bottom, rgb(199, 188, 217), rgb(129, 103, 169)); color: #32383d; font-weight: 700;font-size: 2rem;display: inline-block;text-decoration: none;transition: all 0.5s;position: relative;border: none;cursor: pointer;"%>
    </div>
  </div>
<% end %>

  <h5 style="margin-left: 22px;"><%= link_to "Back", project_path(@project), style: "margin-left: 22px; color: #8167a9ff; text-decoration: none;" %></h5>
<% if @todos.count > 0 %>
  

<div class="wrapper">
  <%# <form class="row row-cols-lg-auto g-3 justify-content-center align-items-center mb-4 pb-2"> %>
  <% @todos.each do |todo| %>
    <% if todo.persisted? %>
      
      
  <ul class="tasks__list">
    <li class="tasks__item">
      <%= todo.name %>
      <div class="tasks__item__configuration">
        <a href="/projects/107/tasks/107/edit?task_id=57">
        <%= link_to edit_project_todo_path(todo.project, todo) do %>
        <i style="font-size: 20px; color: rgb(129, 103, 169);" class="bi bi-pen"></i>
        <% end %>
      <%= link_to [todo.project, todo], 'data-turbo-method': :delete, onclick: "return confirm('Are You Sure!')" do %>
          <i style="font-size: 20px; color: rgb(129, 103, 169);" class="bi bi-trash2"></i>
        <% end %>
                                    
        </div>
    </li>
  </ul><br>
  <% end %>
    <% end %>

  
  
</div>
    <% end %>
<style>
  .wrapper {
    margin: 5em auto;
    max-width: 1000px;
    background-color: rgb(158, 138, 189);
    box-shadow: 0 0 5px 0 rgba(0, 0, 0, 0.06);

    /* height: 60rem; */
      /* background-image: linear-gradient(to right bottom, rgba(250,204,104,0.4), rgba(241,189,170,0.7)); */
      box-shadow: 0 0 10px #dddcdc;
      border-radius: 10px;
  }
  .tasks__list{
        height: 100%;
      overflow: auto;
  }
  .tasks__item {
      width: 90%;
      margin: 2rem auto 0 auto;
      list-style: none;
      padding: 1rem 2rem;
      border-radius: 0.5rem;
      border-left: 15px solid rgb(129, 103, 169);
      background-color: #ffffff;
      display: flex;
      align-items: center;
      justify-content: space-between;
      box-shadow: 0 0 10px #cbb5dd;
  }
  .comments_destroy_svg, .comments_edit_svg {
      width: 30px;
      height: 30px;
      margin-right: 8px;
      transition: transform 0.5s;
  }
</style>

My_basecamp_2-main/app/views/todos/show.html.erb
<p style="color: green"><%= notice %></p>



<div class="slide-container">
  
  <div class="wrapper">
    <div class="clash-card barbarian">
      <div class="clash-card__image--barbarian">
      </div>
      <div class="clash-card__unit-name" style="margin-top: 46px;"><%= @todo.name  %></div>
      <div class="clash-card__unit-description">
      </div>

      <div class="clash-card__unit-stats clash-card__unit-stats--barbarian clearfix">
        <div class="one-third">
          <div class="stat">
          <%= @todo.project.name %>
          <sup><%= @project.id %></sup></div>
          <div class="stat-value">Project Name</div>
        </div>

        <div class="one-third">
          <div class="stat">
          <% @users.each do |user| %>
            
            <% if user.id == @todo.project.user_id %>
            <%= user.username %>
            <% end %>
            
          <% end %>
          </div>
          <div class="stat-value">Creator</div>

        </div>

                <div class="one-third ">
          <div class="stat " >
  <%= link_to "Back", new_project_todo_path(@project), style: "margin-left: 106px;" %>

          </div>
          </div>

        <div class="one-third no-border">

        </div>


      </div>

    </div> <!-- end clash-card barbarian-->
  </div> <!-- end wrapper -->
  
</div> <!-- end container -->


<style>
@import url(https://fonts.googleapis.com/css?family=Lato:400,700,900);
*, *:before, *:after {
  box-sizing: border-box;
}

body {
  background: linear-gradient(to bottom, #8c7a7a 0%, #af877c 65%, #af877c 100%) fixed;
  background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/coc-background.jpg") no-repeat center center fixed;
  background-size: cover;
  font: 14px/20px "Lato", Arial, sans-serif;
  color: #9E9E9E;
  margin-top: 30px;
}

.slide-container {
  margin: auto;
  width: 600px;
  text-align: center;
}

.wrapper {
  padding-top: 40px;
  padding-bottom: 40px;
}
.wrapper:focus {
  outline: 0;
}

.clash-card {
  background: white;
  width: 300px;
  display: inline-block;
  margin: auto;
  border-radius: 19px;
  position: relative;
  text-align: center;
  box-shadow: -1px 15px 30px -12px black;
  z-index: 9999;
}

.clash-card__image {
  position: relative;
  height: 230px;
  margin-bottom: 35px;
  border-top-left-radius: 14px;
  border-top-right-radius: 14px;
}

.clash-card__image--barbarian {
  background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/barbarian-bg.jpg");
}
.clash-card__image--barbarian img {
  width: 400px;
  position: absolute;
  top: -65px;
  left: -70px;
}

.clash-card__image--archer {
  background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/archer-bg.jpg");
}
.clash-card__image--archer img {
  width: 400px;
  position: absolute;
  top: -34px;
  left: -37px;
}

.clash-card__image--giant {
  background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/giant-bg.jpg");
}
.clash-card__image--giant img {
  width: 340px;
  position: absolute;
  top: -30px;
  left: -25px;
}

.clash-card__image--goblin {
  background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/goblin-bg.jpg");
}
.clash-card__image--goblin img {
  width: 370px;
  position: absolute;
  top: -21px;
  left: -37px;
}

.clash-card__image--wizard {
  background: url("https://s3-us-west-2.amazonaws.com/s.cdpn.io/195612/wizard-bg.jpg");
}
.clash-card__image--wizard img {
  width: 345px;
  position: absolute;
  top: -28px;
  left: -10px;
}

.clash-card__level {
  text-transform: uppercase;
  font-size: 12px;
  font-weight: 700;
  margin-bottom: 3px;
}

.clash-card__level--barbarian {
  color: #EC9B3B;
}

.clash-card__level--archer {
  color: #EE5487;
}

.clash-card__level--giant {
  color: #F6901A;
}

.clash-card__level--goblin {
  color: #82BB30;
}

.clash-card__level--wizard {
  color: #4FACFF;
}

.clash-card__unit-name {
  font-size: 26px;
  color: black;
  font-weight: 900;
  margin-bottom: 5px;
}

.clash-card__unit-description {
  padding: 20px;
  margin-bottom: 10px;
}

.clash-card__unit-stats--barbarian {
  background: #EC9B3B;
}
.clash-card__unit-stats--barbarian .one-third {
  border-right: 1px solid #BD7C2F;
}

.clash-card__unit-stats--archer {
  background: #EE5487;
}
.clash-card__unit-stats--archer .one-third {
  border-right: 1px solid #D04976;
}

.clash-card__unit-stats--giant {
  background: #F6901A;
}
.clash-card__unit-stats--giant .one-third {
  border-right: 1px solid #de7b09;
}

.clash-card__unit-stats--goblin {
  background: #82BB30;
}
.clash-card__unit-stats--goblin .one-third {
  border-right: 1px solid #71a32a;
}

.clash-card__unit-stats--wizard {
  background: #4FACFF;
}
.clash-card__unit-stats--wizard .one-third {
  border-right: 1px solid #309eff;
}

.clash-card__unit-stats {
  color: white;
  font-weight: 700;
  border-bottom-left-radius: 14px;
  border-bottom-right-radius: 14px;
}
.clash-card__unit-stats .one-third {
  width: 50%;
  float: left;
  padding: 20px 15px;
}
.clash-card__unit-stats sup {
  position: absolute;
  bottom: 4px;
  font-size: 45%;
  margin-left: 2px;
}
.clash-card__unit-stats .stat {
  position: relative;
  font-size: 24px;
  margin-bottom: 10px;
}
.clash-card__unit-stats .stat-value {
  text-transform: uppercase;
  font-weight: 400;
  font-size: 12px;
}
.clash-card__unit-stats .no-border {
  border-right: none;
}

.clearfix:after {
  visibility: hidden;
  display: block;
  font-size: 0;
  content: " ";
  clear: both;
  height: 0;
}

.slick-prev {
  left: 100px;
  z-index: 999;
}

.slick-next {
  right: 100px;
  z-index: 999;
}
</style>